### ISSUE TITLE
Input should be validated

### ISSUE THREAD

**Issue by lonwillett** [dicekeys/dicekeys-android#113]
I recently discovered that the app doesn't check that the dice are actually a correct set; e.g. it accepts a key with two "_S_" dice and no "_I_" die. It should at least issue a warning when the dice aren't actually {_A_ .. _Z_} - {_Q_}.

**Comment by UppaJung** [comment]
We allow users to mix and match dice from multiple bags, or to create keys with SticKeys that would not be possible with only 25 unique dice.

**Comment by lonwillett** [comment]
So it's a feature, not a bug. Correct? And I can rely on it continuing to work this way in the future?

**Comment by UppaJung** [comment]
Correct.  We've discussed having a warning in certain cases, but it would be overridable.

(e.g. If you've got 5 duplicate letters, it's unlikely a random error.  If you've got only one duplicate/missing letter, maybe we show a warning for that key the first time it is loaded onto the device.)

**Comment by lonwillett** [comment]
OK.
