### ISSUE TITLE
DiceKey dice do not render in "force override dark mode"

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-android#116]
Reported by user

**Comment by JohnLGalt** [comment]
Tested on:

- Pixel 2 XL running Android 11 (Build RP1A.201005.004.A1 (EOL, last available stock Android build for 2 XL)
- Pixel 4 XL Running Android 12 DP2 (Build SPP2.210219.008)

If Developer Option **Override force-dark** is enabled, Dice Keys captured image of dice in tray does not show the dice.

![PXL_20210326_015852083](https://user-images.githubusercontent.com/7432512/112570950-64897f00-8dbd-11eb-9f07-105ba83990a1.jpg)

(Pic is of Pixel 4 XL taken with 2 XL camera - images look same on both phones).

Also referenced in Google Play Dice Keys app review by Aaron Toponce:

https://play.google.com/store/apps/details?id=com.dicekeys.app&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEljGczJxi1FCKomxD-Wm_BnS8IGO2quETCh0cobbt453eiRh9sB0b9gaNU3dNM1uiAB2JdiHyQ31cOnw

Disabling Override setting allows image to be viewed.

**Comment by angelix** [comment]
This is an option intended for Developers to help them with the Dark theme implementation.
 
The issue should be about **Adding support for Dark Theme**.
