### ISSUE TITLE
Add Android-Verification Links to dicekeys.app

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-android#131]
@angelix wrote
> Unfortunately i cannot create it myself as it requires the signing keystore.
> I think the first form is the easiest method to create the file.
> Form
> https://support.google.com/webmasters/answer/6212023
> Command line
> https://developer.android.com/training/app-links/verify-site-associations#web-assoc (edited)

**Comment by angelix** [comment]
Done
https://dicekeys.app/.well-known/assetlinks.json
