### ISSUE TITLE
Bug Report (Ticket 308)

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-android#142]
> Hello, I was testing out the app to see if dicekey was something I wanted to use, and am encountering a problem with saving the dicekey.
> I get the following error when i try to save it to the app:
> "Negative text must be set and non-empty."

**Comment by CaptainSully** [comment]
Hello, I sent the email UppaJung is submitting here.
To expand on this...
After scanning a dicekey with the android app, you can click the phone icon in the upper right and that brings you to the screen that says "Save the DiceKey" (using the centre die) and asks how you would like to unlock the other 24 dice.
When I selected "Use my lock screen unlock options" and then hit save, I got the error stated above ("Negative text must be set and non-empty.")
I just enabled biometrics on my phone today, so I thought I'd try that instead; this time it worked and the dicekey was saved, and unlocking it later seems to work just fine. (trying to use the lock screen options still gives the original error).

For reference I use pattern unlock, there's no pin.

**Comment by angelix** [comment]
@CaptainSully unfortunately i wasn't able to replicated it. What's your Android version?

Maybe the next release will fix this issue as it has a lot of changes.

**Comment by CaptainSully** [comment]
Android version is only 8.0.0, so that wouldn't surprise me.

**Comment by angelix** [comment]
Thank you @CaptainSully, i was able to replicate it in the emulator with Android 8. Fixed in the upcoming release.
