### ISSUE TITLE
Saved DiceKeys inaccessible after new biometrics added

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-android#161]
There are two options for unlocking saved DiceKeys on Android.
@angelix explained: "If a user selects the “screen lock” option, the key is valid even after a new fingerprint is added. Is invalidated only if you disable the lock screen."  If you select the biometrics option, DiceKeys are invalidated whenever biometrics are changed.

One option would be to remove "use only my fingerprint or other biometrics" since this option doesn't clearly provide more security but definitely causes user headaches.

Minimally, the biometrics option should NOT be the default, and should have a warning saying that you will lose access to saved DiceKeys whenever you add a new fingerprint or other biometric.  (The exact wording will depend on up what rules Android actually enforces, which @UppaJung doesn't fully understnad yet.)

**Comment by UppaJung** [comment]
Might be changed via:
https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setInvalidatedByBiometricEnrollment(boolean)

**Comment by UppaJung** [comment]
https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setUserAuthenticationParameters(int,%20int)

It looks like we can actually implement the following options:

1. Allow unlock via knowledge-based PIN/Pattern/Password or biometric  `type=KeyProperties.AUTH_DEVICE_CREDENTIAL|KeyProperties.AUTH_BIOMETRIC_STRONG`.  Should be the DEFAULT.
2. No-biometric (requires PIN/Pattern/Password, `setUserAuthenticationParameters` with `type=KeyProperties.AUTH_DEVICE_CREDENTIAL`).
(https://developer.android.com/reference/android/security/keystore/KeyProperties#AUTH_DEVICE_CREDENTIAL)`
3. Biometric-only with `type=KeyProperties.AUTH_BIOMETRIC_STRONG`

We currently offer (1) and (3) but not (2).  We should make (1) the default and put it up top, and add (2), putting (3) last.  Under option (3) should be a checkbox allowing the user to choose invalidating credentials if biometrics change, and that checkbox should default OFF.

**Comment by angelix** [comment]
I started implement the additional options and came across some issues that are undocumented.
For example  making `setInvalidatedByBiometricEnrollment = false` returns an error (`Key user not authenticated`) when trying to use the cypher on a Pixel 6 device but works on the emulator. By default `setInvalidatedByBiometricEnrollment` is set to `true` btw.

I remember when developed AppKeystore, not all Keystore combinations work on different device and android versions. Our current implementation is the most tested between all android versions and i consider it very stable.

I propose to make option **1)** the default one and make a note to **3)** that the encryption key could be invalidated when you remove all biometrics or add a new one.

I don't think option **2)** is needed.

What do you think?

**Comment by UppaJung** [comment]
# Agreed
 - First and default option is (1): `AUTH_DEVICE_CREDENTIAL|KeyProperties.AUTH_BIOMETRIC_STRONG`
 - Add note for option 3 detailing conditions under which you will lose access to DiceKeys.
 
# Proposed
 - Add a new issue for a later version to implement the checkbox on popular devices that we know support `setInvalidatedByBiometricEnrollment = false` so we can document that we should have this option eventually and it's just a matter of engineering time and device support.  By making a new issue way we don't hold up a new release with all that work.

 # Further discussion
- Option (2) seems needed because in some jurisdictions you can be forced to fingerprint or face unlock your phone but not forced to reveal your PIN/Password/Pattern.  Only option (2) protects saved DiceKeys against this threat model, as well as the threat model where someone uses face or finger unlock while you're asleep (passed out drunk, etc.). Why don't you think it's needed?

**Comment by angelix** [comment]
About option 2) make sense from a legal prospective, not from a technical one. I commented thinking only from technical prospective.

Crypto-based encryption means that the encryption/decryption is handled by a Cipher that is unlocked/managed by Biometrics.

An encryption based only on AUTH_DEVICE_CREDENTIAL, is inferior as is no longer managed by a crypto-based Cipher. It's ok i guess to give that option to the user.

More read:
https://developer.android.com/training/sign-in/biometric-auth#crypto

We also have to deal with many limitations on different Android OS's, eg:
> Optional: Specifies the type(s) of authenticators that may be invoked by BiometricPrompt to authenticate the user. Available authenticator types are defined in BiometricManager.Authenticators and can be combined via bitwise OR. Defaults to:
> BiometricManager.Authenticators.BIOMETRIC_WEAK for non-crypto authentication, or
> BiometricManager.Authenticators.BIOMETRIC_STRONG for crypto-based authentication.
> Note that not all combinations of authenticator types are supported prior to Android 11 (API 30). Specifically, DEVICE_CREDENTIAL alone is unsupported prior to API 30, and BIOMETRIC_STRONG | DEVICE_CREDENTIAL is unsupported on API 28-29. Setting an unsupported value on an affected Android version will result in an error when calling build().

**Comment by angelix** [comment]
I can make some changes in #162, to use the same keystore settings as solution 1) and only ask for PIN/Pattern/Password excluding biometrics. Same security as 1) without biometrics.
