### ISSUE TITLE
API using Android intents should not launch long-defunct trustedapp project

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-android#165]
In removing the no-longer-used truestedapp project, I discovered that we used to support intent APIs and that the client would launch that long-defunct app.

https://github.com/dicekeys/dicekeys-android/blob/4dc8bd8d8b6a320e3b125647626c07bc52daae8b/api/src/main/java/org/dicekeys/api/DiceKeysIntentApiClient.kt#L19

https://github.com/dicekeys/dicekeys-android/blob/65c3400d3f51a8b70c02306285c5687e95601ada/api/src/main/java/org/dicekeys/api/ApiStrings.kt#L7

We need to

- [ ] Decide whether to keep intent-based APIs
- [ ] If so, fix the above.  If not, remove the client and update documentation.

**Comment by angelix** [comment]
Intent based API is not so flexible compared to the app links based one. For example having a wrong package name is a blocker, and you cannot change the package name if your app is published.
