### ISSUE TITLE
Fixes to address/purpose modal

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-android#167]
- [x] "Describe your recipe with" => "What is this recipe for?"
- [x] The "close" button is really an "enter" button, so it should be renamed "enter".
- [x] Spelling error "parselabel" => "parseable"
- [x] close/enter button hidden when keyboard is visible (see below screenshot).  Can we design the modal so that it automatically stays above the keyboard when the keyboard enters?  If not, how is this typically solved?

![enter-button-hidden](https://user-images.githubusercontent.com/8259431/166259802-c9ebca31-ce82-4053-a896-9b495a15f6b9.jpeg)

On mobile platforms, perhaps we don't actually edit raw json but instead allow importing of recipes and pasting of json from the clipboard, assuming that those who need specialized recipes will be getting them from somewhere that supports rich editing?

**Comment by angelix** [comment]
>  The "close" button is really an "enter" button, so it should be renamed "enter".
Maybe "OK" is better?

**Comment by UppaJung** [comment]
"OK" implies agreement with something.  We're not asking them a question.
"enter", "done", or "finish" imply "I've completed putting the thing here that I want."
