### ISSUE TITLE
Freeze when saving a DiceKey

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-android#191]
User-reported issue:

> I reinstalled the Dicekeys app on my Android smartphone and now I have another issue. 
> I can load my dicekey but if I want to save the dicekey to my phone, the app displays me 3 options. Whatever option I select it pops up the Android fingerprint dialog box.After I apply a correct fingerprint the pop-up reappears again and I cannot leave the save screen. It keeps popping up the fingerprint dialog box.
> Bottom line : I cannot store the dicekey on my phone.
> 
> I currently using : Android version 12 . Dicekey version : 1.07 Build 8
> 
> thx for helping me out !

They had been having problems with a previous version and upgraded, so I wonder if this could have to do with old data sticking around?

**Comment by angelix** [comment]
@UppaJung I couldn't reproduce with various settings.

Some information could be useful like:
- Phone model
- Is it a Custom ROM?
- Is a new/clear installation?
- Is Lock Screen on? (i think it is, but just to be sure)

**Comment by UppaJung** [comment]
This was an uninstall and re-install (see below).

Fixed after re-try.  Lowering priority in hopes this was a transitional issue for new users.  Worth an hour of further investigation and, if no obvious cause, we can wait to see if we see it again.

> But in the meantime, did it all over again and now it works. I have no clue what has changed but now it works again. 
>

**Comment by UppaJung** [comment]
Fixed in 1.12
