### ISSUE TITLE
Prevent BIP39 generation if secret bytes are not multiple of 32bits

### ISSUE THREAD

**Issue by angelix** [dicekeys/dicekeys-android#203]
From the [BIP39 Spec](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki)

```
The mnemonic must encode entropy in a multiple of 32 bits.
```

If a recipe uses `lengthinBytes` the secret bytes may be not multiple of 32bits. In that case warn user about this limitation.

**Comment by UppaJung** [comment]
I'd suggest we only show the BIP39 option for secrets of size other than 32 bytes.  (what we do in TypeScript now)

**Comment by angelix** [comment]
I suggest to show BIP39 options for 16 & 32 bytes. 
16 bytes create a 12 word mnemonic, i think is the most common mnemonic size used by users.

**Comment by UppaJung** [comment]
The TypeScript implementation doesn't currently support that.  It could.  The question is, if users are using a DiceKey, would there be any reason for them to use the less secure option of 16 bytes?  They're going to be generating a new BIP39 secret regardless.

**Comment by angelix** [comment]
It's easier to enter it on a sw/hw wallet, nothing else.
Let's see if there are requests for it.
