### ISSUE TITLE
Implement encrypted DiceKey storage

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-android#32]
- [x] A put function to store a DiceKey into a file (using human readable format) that will be encrypted with a key protected by the OS
- [x] A get function that decrypts and returns a DiceKey if the user re-authenticates using a PIN, Fingerprint, or Face

The Android implementation of the DIceKey object, and the encoder/decoder to human readable form, can be found in: https://github.com/dicekeys/dicekeys-android/blob/main/dicekey/src/main/java/org/dicekeys/dicekey/DiceKey.kt

The iOS implementation of encrypted storage and authenticated decryption is at: https://github.com/dicekeys/dicekeys-app-ios/blob/main/DiceKeys/Core/DiceKey/EncryptedDiceKeyFileAccessor.swift

**Comment by angelix** [comment]
Implemented in #37
