### ISSUE TITLE
Ensure new Android developers can get started with keys for development use

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-android#35]
@angelix wrote: we can also have development ones to give to the developers, and have the production one more restricted

@UppaJung wrote: okay, how about instead of creating a dummy, you create the reference developer ones and put instructions for developers to use them into the README?

@angelix wrote: sure

**Comment by angelix** [comment]
PR #36 fixes the build process for debug builds. No need to sign the debug build or have a keystore.
More work needs to be done for keystore handling but first we have to clean the modules and keep only what's needed.
