### ISSUE TITLE
Replicate DiceKeyCenterFaceOnlyView from Apple app

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-android#44]
Needed for App main page code being rendered by @angelix.

Use components for drawing DiceKeys from #31.

@iOSMahesh, is this something you think you could handle?
@bakhtiyork and @angelix, were either of you already assuming you'd be taking this on as part of an existing issue?

**Comment by iOSMahesh** [comment]
@angelix from which branch I have to render main page code ?
Yes, I'll give my try on this.

Let me know if @bakhtiyork or @angelix taking this issue ?

**Comment by bakhtiyork** [comment]
I can take the issue because it is closely related to other UI widgets

**Comment by UppaJung** [comment]
Looks good in current branch so I'm assuming this should have been linked to a prior PR and closed.
