### ISSUE TITLE
Cluttered home screen with multiple scanned keys

### ISSUE THREAD

**Issue by atoponce** [dicekeys/dicekeys-android#86]
When multiple keys are saved, the home screen gets cluttered to the point that text begins to disappear.

![dicekeys-android](https://user-images.githubusercontent.com/699572/110140474-5e414d80-7d91-11eb-85ea-ebbdff1bb6b8.png)

**Comment by UppaJung** [comment]
Thanks @atoponce.  Prioritizing for the 1.1 release.
