### ISSUE TITLE
Typo and grammar

### ISSUE THREAD

**Issue by atoponce** [dicekeys/dicekeys-android#96]
Line 59 of [app/src/main/res/values/strings.xml](https://github.com/dicekeys/dicekeys-android/blob/main/app/src/main/res/values/strings.xml#L59) has "passowrd" instead of "password". This also appears on line 13 of [trustedapp/src/main/res/values/strings.xml](https://github.com/dicekeys/dicekeys-android/blob/main/trustedapp/src/main/res/values/strings.xml#L13).

This shows up in the app under the "SoloKey" and "Secrets" menus:

> "if you need multiple passwords for a single website or service, change sequence number to create additional passowrd"

Capitalization, grammar, and punctuation should probably also be fixed (additions emphasized):

> "**I**f you need multiple passwords for a single website or service, change **the** sequence number to create additional password**s.**"

**Comment by UppaJung** [comment]
Thanks so much @atoponce.  Those fixes should get propagated into the next release!

Also, since you're already doing all the work needed to submit a PR, do know that welcome external PRs if you want GitHub to reflect your contribution counts.
